train: ./train/images
val: ./validation/images
test: ./test/images

names:
  0: Apple Scab Leaf
  1: Apple leaf
  2: Apple rust leaf
  3: Bell_pepper leaf
  4: Bell_pepper leaf spot
  5: Blueberry leaf
  6: Cherry leaf
  7: Corn Gray leaf spot
  8: Corn leaf blight
  9: Corn rust leaf
  10: Peach leaf
  11: Potato leaf
  12: Potato leaf early blight
  13: Potato leaf late blight
  14: Raspberry leaf
  15: Soyabean leaf
  16: Squash Powdery mildew leaf
  17: Strawberry leaf
  18: Tomato Early blight leaf
  19: Tomato Septoria leaf spot
  20: Tomato leaf
  21: Tomato leaf bacterial spot
  22: Tomato leaf late blight
  23: Tomato leaf mosaic virus
  24: Tomato leaf yellow virus
  25: Tomato mold leaf
  26: Tomato two spotted spider mites leaf
  27: grape leaf
  28: grape leaf black rot

